sudo: required
language: cpp
services:
  - docker
before_install:
  - docker build -t smile . 
  - docker run  -itd --name build smile 
script:
  - docker exec build cmake -DCMAKE_BUILD_TYPE=Debug .
  - docker exec build make  
  - docker exec build make test
  - docker exec build cmake -DCMAKE_BUILD_TYPE=Release .
  - docker exec build make  
  - docker exec build make test
